improve: batch calc with Requests.csv

diff --git a/scripts/calc_result b/scripts/calc_result
--- a/scripts/calc_result
+++ b/scripts/calc_result
@@ -12,13 +12,17 @@
 teamsCSV="$ETROBO_ROOT/dist/Teams.csv"
 divisionsCSV="$ETROBO_ROOT/dist/Divisions.csv"
 
+start_time="`date "+%s"`"
+
 # show usage
 if [ "$1" == "usage" ] || [ "$1" == "--help" ]; then
-    echo "usage: calc_result [serv|ranking </path/to/relayFolder>] [YEAR] [<CLASS>] /path/to/CSV"
+    echo "usage: calc_result [request <teamID>|serv|ranking </path/to/relayFolder>] [YEAR] [<CLASS>] /path/to/CSV"
     echo
     echo "Calcuate preliminary Result Time from a CSV file."
+    echo "  env ... set datum to ENVVAR"
     echo
-    echo "  serv ... run on server which running at </path/to/relayFolder>"
+    echo "  request ... run on server which running at </path/to/relayFolder>, use <teamID> forcely"
+    echo "  serv    ... run on server which running at </path/to/relayFolder>"
     echo "  ranking ... run on server with the ranking site at </path/to/relayFolder>"
     echo
     echo "  YEAR(default:'2021'): specify the year of competition rules"
@@ -34,13 +38,19 @@ fi
 
 # determine options
 unset serv
+unset teamID
 unset relayFolder
 unset trigger
 unset lock
-if [ "$1" == "serv" ] || [ "$1" == "ranking" ]; then
+if [ "$1" == "serv" ] || [ "$1" == "ranking" ] || [ "$1" == "request" ]; then
     serv="$1"
-    relayFolder="$2"
-    shift 2
+    shift
+    if [ "$serv" == "request" ]; then
+        teamID="$1"
+        shift
+    fi
+    relayFolder="$1"
+    shift
 
     destResult="$relayFolder/common/results.csv"
     destRanking="$relayFolder/Ranking/results.csv"
@@ -74,23 +84,37 @@ csv_filename="$(basename $csv)"
 
 unset ranking
 
-# lookup teamID
-unset teamID
-if [ -n "$serv" ]; then
-    requestID="`echo \"$csv_filename\" | sed -E 's/^(.*)\.csv/\1/' | grep -E '^[0-9|a-f|A-F]{8}-*[0-9|a-f|A-F]{4}-*[0-9|a-f|A-F]{4}-*[0-9|a-f|A-F]{4}-*[0-9|a-f|A-F]{12}$'`"
-    if [ -n "$requestID" ]; then
-        teamID="`ETroboSimRunner.Relay.sh lookup $relayFolder $requestID`"
-        if [ "$?" != "0" ]; then
-            echo "FATAL ERROR: teamID ($requestID) lookup failed. "
+# get requestID & lookup teamID
+unset requestID
+if [ -n serv ]; then
+    classPrefix=`echo $csv_filename | grep -E '^A_|^P_|^E_|^S_' | awk '{print substr($0,1,1)}'`
+    case "$classPrefix" in
+        "A" ) class="advanced" ;;
+        "P" ) class="primary" ;;
+        "E" ) class="entry" ;;
+    esac
+    if [ -n "$classPrefix" ]; then
+        requestID="`echo $csv_filename | sed -E 's/^.{1}_(.*).zip$/\1/'`" 
+    else
+        requestID="`echo $csv_filename | sed -E 's/^(.*).zip$/\1/'`" 
+    fi
+
+    if [ -z "teamID" ]; then
+        if [ -n "$requestID" ]; then
+            teamID="`ETroboSimRunner.Relay.sh lookup $relayFolder $requestID`"
+            if [ "$?" != "0" ]; then
+                echo "FATAL ERROR: teamID ($requestID) lookup failed. "
+                exit 1
+            fi
+        else
+            echo "FATAL ERROR: this filename isn't contain a requestID."
             exit 1
         fi
-    else
-        echo "FATAL ERROR: this filename isn't contain a requestID."
-        exit 1
     fi
     ranking[0]="$requestID"
     ranking[1]="$teamID"
 fi
+
 # determine auto modes
 unset categoryCode
 if [ "$class" == "auto" ]; then
@@ -166,13 +190,20 @@ for ((i=0; i<${#fields[@]}; i++)); do
     fi
     mapper="${mapper}\"${fields[$i]}\":.[$i]"
 done
-result=`cat "$1" | sed -e '1d' -e 's/\r//g' \
+#result=`cat "$1" | sed -e '1d' -e 's/\r//g' \
+# | jq -csR 'split("\n")|map(split(","))|map({'$mapper'})|del(.[][]|nulls)' \
+# | sed -E 's/,\{\}//' | jq -c .`
+#lastIndex=`echo "$result" | jq '.|length-1'`
+
+start=`cat "$1" | sed -e '1d' -e 's/\r//g' | grep -E ',GO$' | head -n 1 \
  | jq -csR 'split("\n")|map(split(","))|map({'$mapper'})|del(.[][]|nulls)' \
- | sed -E 's/,\{\}//' | jq -c .`
-lastIndex=`echo "$result" | jq '.|length-1'`
+ | sed -E 's/,\{\}//' | jq -c .[0]`
+end=`cat "$1" | tail -n 1 | sed -e 's/\r//g' \
+ | jq -csR 'split("\n")|map(split(","))|map({'$mapper'})|del(.[][]|nulls)' \
+ | sed -E 's/,\{\}//' | jq -c .[0]`
 
 # determine course
-coursePrefix=`json result.[0].Filename | sed -E 's/^([LR])_.*$/\1/'`
+coursePrefix=`json start.Filename | sed -E 's/^([LR])_.*$/\1/'`
 course="left"
 ranking[3]='L'
 if [ "$coursePrefix" == "R" ]; then
@@ -211,6 +242,26 @@ if [ "$year" == "2021" ]; then
         ranking[$i]=""
     done
 
+    # bonus defaults
+    if [ "$class" == "entry" ]; then
+        ranking[7]=FALSE
+        ranking[8]=FALSE
+        ranking[9]=0
+    elif [ "$class" == "primary" ]; then
+        ranking[7]=FALSE
+        ranking[8]=FALSE
+        ranking[10]=FALSE
+        ranking[11]=6
+        ranking[12]=FALSE
+        ranking[13]=FALSE
+    elif [ "$class" == "advanced" ]; then
+        ranking[14]=0
+        ranking[15]=0
+        ranking[16]=0
+        ranking[17]=0
+        ranking[18]=0
+    fi
+
     # time0
     time0='
     { 
@@ -236,8 +287,8 @@ if [ "$year" == "2021" ]; then
         "MeasurementMode": "READY"
     }'
     time0="`echo "$time0" | jq -c .`"
-    start=`echo "$result" | jq '.[]|select(.Counter=="0" and .MeasurementMode=="GO")'`
-    end=`json result.[$lastIndex]`
+#    start=`echo "$result" | jq '.[]|select(.Counter=="0" and .MeasurementMode=="GO")'`
+#    end=`json result.[$lastIndex]`
 
     # start time validation
     unset status
@@ -274,22 +325,16 @@ if [ "$year" == "2021" ]; then
         # passed START gate
         if [ "`json end.RUN_TIME`" != "0" ]; then
             # passed GATE1 gate
-            ranking[7]="FALSE"
             if [ "`json end.GATE1`" != "0" ]; then
                 if [ "$class" != "advanced" ]; then
                     bonus=$(($bonus+2000))
                     ranking[7]="TRUE"
-                else
-                    ranking[7]=""
                 fi
                 # passed GATE2 gate
-                ranking[8]="FALSE"
                 if [ "`json end.GATE2`" != "0" ]; then
                     if [ "$class" != "advanced" ]; then
                         bonus=$(($bonus+2000))
                         ranking[8]="TRUE"
-                    else
-                        ranking[8]=""
                     fi
                     # passed GOAL gate
                     if [ "`json end.GOAL`" != "0" ]; then
@@ -304,7 +349,6 @@ if [ "$year" == "2021" ]; then
                         # mission bonus for primary class
                         elif [ "$class" == "primary" ]; then
                             # passed slalom
-                            ranking[10]="FALSE"
                             if [ "`json end.SLALOM`" != "0" ]; then
                                 bonus=$(($bonus+5000))
                                 ranking[10]="TRUE"
@@ -314,8 +358,6 @@ if [ "$year" == "2021" ]; then
                                 bonus=$(($bonus+${pets[${ranking[11]}]}))
                             fi
                             # garage in
-                            ranking[12]="FALSE"
-                            ranking[13]="FALSE"
                             if [ "`json end.GARAGE_STOP`" != "0" ]; then
                                 bonus=$(($bonus+5000))
                                 ranking[12]="TRUE"
@@ -410,6 +452,7 @@ if [ "$year" == "2021" ]; then
             touch "destTrigger"
         fi
     fi
+    echo "done: $((`date "+%s"` - start_time)) secs"
 else
     echo "FATAL ERROR: no competion rules for $year."
     exit 1
